### ISSUE TITLE
add icons per node

### ISSUE THREAD

**Issue by vdidonato** [emiliorizzo/vue-d3-network#2]
Other than the colors, it would be nice to have the possibility to use figures as background of the nodes. This way one could use icons and represent different types of nodes with different icons. This would require to render the nodes as svg groups and then append to each group the circle and an svg figure with its xlink:href attribute.

Do you see any easy workaround to this?

**Comment by emiliorizzo** [comment]
I have the same problem in a project that uses this component.
The solution is to add icons per node. (in current version you can use svg icons, but only one icon for all nodes).
I'm working on new version with per node icons
I don't use svg symbols because the conversion to canvas is more complex, and I try to maintain the hot switch between canvas and svg renderers.
Comments and ideas are welcome.

**Comment by vdidonato** [comment]
Another option would be to make the background into a pattern. So you define your patterns this way:

    <defs>
      <pattern id="img1" width="100" height="100">
        <image xlink:href="icon.png" x="0" y="0" width="100" height="100"></image>
      </pattern>
    </defs>

and then you would do something like:

    <circle .....  fill="url(#img1)"></circle>

**Comment by emiliorizzo** [comment]
Mixing images with vectors... mmm... dirty approach.
