### ISSUE TITLE
Bounded force layout

### ISSUE THREAD

**Issue by vdidonato** [emiliorizzo/vue-d3-network#6]
I have a large disconnected graph and my nodes are going out of the bounding box. I am trying to force the nodes positions to keep them on the borders and to obtain something like https://bl.ocks.org/mbostock/1129492. It would be nice to have this option.

Unfortunately I'm really new to vue and I'm not sure how to proceed: I see I could listen for the 'tick' event on the simulation object but apparently your vue implementation works a little bit different...

**Comment by emiliorizzo** [comment]
Hi, in my vue implementation the dom render is managed by vue.
I dont use any of d3 methods to write the dom. I use a vue template.
I think this approach is better. You can read about this: (p ex) here: https://tyronetudehope.com/2016/12/13/composing-d3-visualizations-with-vuejs/
or here: http://www.adeveloperdiary.com/react-js/integrate-react-and-d3/ (this is for react, but is the same concept)

Your comment its funny, because two days ago I saw the same example... and i think to implement in the future.

In the current version of component, you can maintain the nodes grouped decrementing the 'force' option  value: https://jsfiddle.net/emii/vffhf9Lg/4/
Thanks, regards
