### ISSUE TITLE
Graph freezes or breaks upon removing links

### ISSUE THREAD

**Issue by N-Desmarais** [emiliorizzo/vue-d3-network#85]
Basically the title, I think I might be doing it wrong since you seem to have done this in your exmaple.

**Comment by N-Desmarais** [comment]
I seem to have solved it, the issue was that there was a gap in the numbering of node or link id's

**Comment by N-Desmarais** [comment]
Actually that didn't seem to fix it, just made it happen less. To give some more detail:
I have a function that I want to delete many nodes, it also needs to go through and delete their attached links. I'm doing so by constructing new links / edges arrays and then assigning them.

This process works sometime but other times I get something like this:
[Vue warn]: Error in callback for watcher "netLinks": "Error: missing: 9"
 
Its always referring to an id that's missing from nodes, but I can't seem to figure out why it wants that id to be there, or how to correctly remove items from the links/nodes arrays.

**Comment by N-Desmarais** [comment]
Here is where I implemented the deletion:
https://github.com/JPWeir/Graf/blob/master/Vue/graf/src/graf_tools.js

Its very hacky, originally I was just splicing items out of the arrays. I got to this point after alot of trial and error as well as looking at your example.

**Comment by N-Desmarais** [comment]
yea im dumb

**Comment by jonabox** [comment]
Hi I think have the same issue as you, basically have to remove a bunch of links but by using the `removeLink` method in this repo's [example code](https://github.com/emiliorizzo/vue-d3-network/blob/master/src/example/d3-net-example.vue), the wrong link gets removed sometimes. I think the problem is with the `.index` property not updating quickly enough when many links are removed. I went ahead and reproduced your fix below for context.

```javascript
removeSimLink(link_id) {
        // find index of link_id and splice
        let index = this.links.findIndex((link) => { link.id = link_id });

        this.links.splice(index, 1);
    }
```

Here's, the faulty removeLink method from the example code:

```javascript
   removeLink(link) {
      this.unSelectLink(link.id);
      this.links.splice(link.index, 1);
    }

```

I'm still trying to figure out where the `.index` property comes from. Perhaps @emiliorizzo could provide some insight.

**Comment by N-Desmarais** [comment]
Hey,

I fixed this a while back so I don't remember 100% but I believe you need to reassign the entire node or links array.

Emilio doesn't seem to support this anymore and I've opted to use d3-force instead of this wrapper I recommend you do the same.

**Comment by jonabox** [comment]
Thanks for replying @N-Desmarais, and yes I just reassigned the entire links array using the filter method and works fine. I'd use d3-force but there's still a lot of functionality that this project already abstracted away for me. But I might reconsider in the future.
